plugins {
	id 'java'
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

ext.mod_version = "${project.mod_base_version}+${project.minecraft_version}"
version = ext.mod_version

processResources {
	inputs.properties([
			"mod_version": project.mod_version,
			"supported_minecraft_versions": project.supported_minecraft_versions,
			"loader_version": project.loader_version,
	])

	filesMatching("fabric.mod.json") {
		expand([
				mod_version: project.mod_version,
				supported_minecraft_versions: project.supported_minecraft_versions,
				loader_version: project.loader_version,
		])
	}
}

java {
	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = project.java_version.toInteger()
}
