# Mod version
mod_base_version=2.0.0

# Minecraft/Java version
# Also hardcoded in fabric.mod.json and *.mixin.json
minecraft_version=26.3
java_version=25
supported_minecraft_versions=>=26.3

# Fabric versions -- check these on https://fabricmc.net/develop
# Also hardcoded in fabric.mod.json
loader_version=0.19.5
loom_version=1.17.21
