# Minecraft Properties
# For changes in new Minecraft, see https://docs.neoforged.net/primer/docs/
java_version=25
minecraft_version=26.3
supported_minecraft_versions=>=26.3

# Mod Properties
mod_base_version=2.0.0
rootProject.name=statuseffecttimer

# Fabric
# Check for latest at https://fabricmc.net/develop
loader_version=0.19.5
loom_version=1.17.21

# Spotless
# Check for latest at https://plugins.gradle.org/plugin/com.diffplug.spotless
spotless_version=8.10.2
# Check for latest at https://plugins.gradle.org/plugin/com.palantir.java-format-spotless
spotless_palantir_version=2.98.0
# Check for latest at https://github.com/google/gson/releases
spotless_gson_version=2.14.0
# Check for latest at https://groovy.jfrog.io/ui/native/plugins-release/org/codehaus/groovy/groovy-eclipse-integration/
spotless_greclipse_version=4.40

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
